### ISSUE TITLE
[Enhancement] Let setup deletes existing build directory

### ISSUE THREAD

**Issue by miroi** [dev-cafe/autocmake#209]
Hi Rado,

sometimes it would help is setup overwrites (delete and start again) the build directory so that we avoid "rm -rf build" before. What do you say ?

**Comment by bast** [comment]
I am not rejecting the idea but is this a problem? Do you need to do that often? We could avoid it but I try to understand the pros and cons first.

**Comment by miroi** [comment]
Well, for the sake of minimizing the number of unnecessary  functionalities, I am rejecting this idea for now.

Because everybody can add "/bin/rm -rf build" before his setup command.

**Comment by bast** [comment]
I did not want to reject it. It is possibly a good idea. Just trying to figure out in which situation we need to remove the build directory?

**Comment by miroi** [comment]
In autocmake tests you had to attache date-time string to the build directory names because setup was not rewriting existing build directories.

**Comment by bast** [comment]
Aha - I see. Let's reopen it and think about it. Perhaps it is better if we allow overwriting.

**Comment by miroi** [comment]
Well, by default let do not overwrite. Rather, overwrite with special flag and with warning unto user:  watch up that you do not destroy working build. 

Buid/ directories might be large (DIRAC's case). In such cases overwrite seem be reasonable...

**Comment by bast** [comment]
I think the risk that I accidentally reset an existing build directory is bigger than the effort to remove the build directory first. We developers compile very often but users sometimes compile only twice a year and it would be annoying to get a build directory wiped by accidentally running setup.
