### ISSUE TITLE
[Discussion] move this repo to another org

### ISSUE THREAD

**Issue by bast** [dev-cafe/autocmake#244]
Motivation is that other projects under the current org (coderefinery) and this repo overlap in terms of developers only in one person (me). This increases noise for others and also forces me to create disjoint teams with essentially non-overlapping interests. This repo is also not really a deliverable of the CodeRefinery project. Of course current bonus (and original motivation) is increased visibility.

One suggestion that @robertodr and I discussed today is to move this to https://github.com/dev-cafe/. Are there objections or other suggestions?

**Comment by bast** [comment]
We will move to https://github.com/dev-cafe/.

**Comment by robertodr** [comment]
:+1:

**Comment by bast** [comment]
And we have moved.

**Comment by bast** [comment]
Reopening until I adapt docs.
